jobs:
  include:
    - stage: Build
      language: csharp
      dist: xenial
      mono: none
      dotnet: 3.1
      install:
        - dotnet clean
        - dotnet restore
      script:
        - dotnet build

    - stage: Deploy
      language: csharp
      dist: xenial
      mono: none
      dotnet: 3.1
      env:
        - VERSION=1.0.0.$TRAVIS_BUILD_NUMBER
        - PACKAGE_FILENAME_WITHOUT_EXTENSION=nanny_$VERSION
        - PACKAGE_FILENAME=$PACKAGE_FILENAME_WITHOUT_EXTENSION.deb
      script:
        - make release
      before_deploy:
        - git config --local user.name $GIT_USERNAME
        - git config --local user.email $GIT_EMAIL
        - git tag $VERSION
      deploy:
        provider: releases
        api_key: $GITHUB_OAUTH_TOKEN
        file: $PACKAGE_FILENAME
        skip_cleanup: true

stages:
#  - name: Build
#    if: type != pull_request
  - name: Deploy
    if: branch = master AND type != pull_request
branches:
  only:
    - /.*/
notifications:
  email: false
