jobs:
  include:
    - stage: Build
      language: csharp
      dist: xenial
      mono: none
      dotnet: 3.1
      install:
        - dotnet clean
        - dotnet restore
      script:
        - dotnet build

    - stage: Tag
      language: minimal
      script:
        - git config --local user.name $GIT_USERNAME
        - git config --local user.email $GIT_EMAIL
        - git tag $VERSION

    - stage: Deploy_Debian
      language: csharp
      dist: xenial
      mono: none
      dotnet: 3.1
      env:
        - VERSION=1.0.0.$TRAVIS_BUILD_NUMBER
        - PACKAGE_FILENAME_WITHOUT_EXTENSION=nanny_$VERSION
        - PACKAGE_FILENAME=$PACKAGE_FILENAME_WITHOUT_EXTENSION.deb
      script:
        - make release-deb
      deploy:
        provider: releases
        api_key: $GITHUB_OAUTH_TOKEN
        file: $PACKAGE_FILENAME
        skip_cleanup: true

    - stage: Deploy_Brew
      language: csharp
      dist: xenial
      mono: none
      dotnet: 3.1
      env:
        - VERSION=1.0.0.$TRAVIS_BUILD_NUMBER
        - PACKAGE_FILENAME=nanny_$VERSION.tar.gz
      script:
        - make release-brew
      deploy:
        provider: releases
        api_key: $GITHUB_OAUTH_TOKEN
        file: $PACKAGE_FILENAME
        skip_cleanup: true

stages:
  - name: Build
    if: type != pull_request
  - name: Tag
    if: branch = master AND type != pull_request
  - name: Deploy_Debian
    if: branch = master AND type != pull_request
  - name: Deploy_Brew
    if: branch = master AND type != pull_request
branches:
  only:
    - /.*/
notifications:
  email: false
