jobs:
  include:
    - stage: Build
      language: csharp
      dist: xenial
      mono: none
      dotnet: 3.1
      install:
        - dotnet clean
        - dotnet restore
      script:
        - dotnet build

    - stage: Tag
      language: minimal
      dist: xenial
      mono: none
      dotnet: 3.1
      env:
        - VERSION=1.0.0.$TRAVIS_BUILD_NUMBER
      before_deploy:
        - git config --local user.name $GIT_USERNAME
        - git config --local user.email $GIT_EMAIL
        - git tag $VERSION
      deploy:
        provider: releases
        api_key: $GITHUB_OAUTH_TOKEN

    - stage: Release
      language: csharp
      dist: xenial
      mono: none
      dotnet: 3.1
      env:
        - VERSION=1.0.0.$TRAVIS_BUILD_NUMBER
        - PACKAGE_FILENAME_WITHOUT_EXTENSION=nanny_$VERSION
        - PACKAGE_FILENAME=$PACKAGE_FILENAME_WITHOUT_EXTENSION.deb
      script:
        - make release-deb
      deploy:
        provider: releases
        api_key: $GITHUB_OAUTH_TOKEN
        file: $PACKAGE_FILENAME
        skip_cleanup: true

    - stage: Release
      language: csharp
      dist: xenial
      mono: none
      dotnet: 3.1
      env:
        - VERSION=1.0.0.$TRAVIS_BUILD_NUMBER
        - PACKAGE_FILENAME=nanny_$VERSION.tar.gz
      script:
        - make release-brew
      deploy:
        provider: releases
        api_key: $GITHUB_OAUTH_TOKEN
        file: $PACKAGE_FILENAME
        skip_cleanup: true

    - stage: Publish
      language: minimal
      dist: xenial
      env:
        - VERSION=1.0.0.$TRAVIS_BUILD_NUMBER
      script:
        - make publish-brew 
      deploy:
        provider: pages
        token: $GITHUB_OAUTH_TOKEN
        committer_from_gh: true
        skip_cleanup: true
        keep_history: true
        local_dir: Packaging/dist/brew
        repo: kolenkainc/homebrew-nanny
        target_branch: master

stages:
  - name: Build
    if: type != pull_request
  - name: Tag
    if: branch = master AND type != pull_request
  - name: Release
    if: branch = master AND type != pull_request
  - name: Publish
    if: branch = master AND type != pull_request
branches:
  only:
    - /.*/
notifications:
  email: false
