jobs:
  include:
    - stage: Build
      language: csharp
      dist: xenial
      mono: none
      dotnet: 3.1
      install: 
        - dotnet clean
        - dotnet restore
      script:
        - dotnet build

    - stage: Deploy
      language: csharp
      dist: xenial
      mono: none
      dotnet: 3.1
      script:
        - git config --local user.name $GIT_USERNAME
        - git config --local user.email $GIT_EMAIL
        - ./Scripts/set_version.sh
      before_deploy:
        - make release
      deploy:
        provider: releases
        api_key: $GITHUB_OAUTH_TOKEN
        file: $PACKAGE_FILENAME
        skip_cleanup: true

stages:
  - name: Build
    if: type != pull_request
  - name: Deploy
    if: branch = master AND type != pull_request
branches:
  only:
    - /.*/
notifications:
  email: false
